<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Interventions_event_item56002</name>
   <tag></tag>
   <elementGuidId>07165e16-fcc4-4146-ad33-4be54a4d2d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event_item_56002</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='event_item_56002']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb2c7fe0-5066-4f81-bb21-9765d5ba72c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display-inline-block single_line_checkbox</value>
      <webElementGuid>141e1b8a-73b3-44cb-bd03-68961a2b223f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group-ids</name>
      <type>Main</type>
      <value>[8706,8708]</value>
      <webElementGuid>72b6aaca-f78e-4eb8-a5d0-516dd9cfe09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2de1fc94-96da-49b1-9510-fdc1f597d9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>723ca800-31d0-444b-96f2-be121c04e3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>event_item[56002]</value>
      <webElementGuid>35f630fc-fe73-4eb7-8974-4baed42fe97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event_item_56002</value>
      <webElementGuid>3c0d9c3e-0385-4f72-a110-d774938d5b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event_item_56002&quot;)</value>
      <webElementGuid>17efaf24-5b1e-44ec-b42f-87dca68991b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='event_item_56002']</value>
      <webElementGuid>8004ee45-fff9-4007-bdf3-b41a4e6a0639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='event_items_list']/li/input[2]</value>
      <webElementGuid>1942fa23-8cb8-4622-917e-a512224bb17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>e521219b-df31-4c02-acb5-dc10f4dac609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'event_item[56002]' and @id = 'event_item_56002']</value>
      <webElementGuid>fffcf713-dc2f-480c-b563-2cd8043a65fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
