<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Visit Notes_commit</name>
   <tag></tag>
   <elementGuidId>8755b72e-bfe6-482c-afd3-7fd673d7a308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_and_view_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='save_and_view_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>120d786a-5e73-4b75-becf-c3597242c01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ef6f5241-d353-41d9-b956-bf419b5e2b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commit</value>
      <webElementGuid>aab26e63-267f-4c56-93e8-d8d9638a276b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Generate Face to Face Visit and View</value>
      <webElementGuid>d349ceb0-f787-4a9b-b4e7-69c22811af08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-with</name>
      <type>Main</type>
      <value>Generating...</value>
      <webElementGuid>ec64b411-00b7-4a4e-80f8-a9bca1892414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success save_button save_event_button</value>
      <webElementGuid>c722dce9-6a02-47ea-858d-672a5b99c331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_and_view_btn</value>
      <webElementGuid>fb1ddf50-c057-4d72-a62f-62d59fa8f1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_and_view_btn&quot;)</value>
      <webElementGuid>3143385f-e3af-44e2-ae6a-e9ae451520d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='save_and_view_btn']</value>
      <webElementGuid>23ada457-6a14-44e8-b53d-4307274a3a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_event']/div[10]/div/input[2]</value>
      <webElementGuid>3ef04201-1d47-471a-874b-72ef84e1780d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input[2]</value>
      <webElementGuid>77cda417-9e2e-4d81-84e5-de60f5e88074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'commit' and @id = 'save_and_view_btn']</value>
      <webElementGuid>be46b7b5-8eaf-4d09-9b75-6f62e67f40bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
